CREATE TABLE IF NOT EXISTS `lxpm_feishu_style_category_match` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `record_id` VARCHAR(100) NOT NULL COMMENT '飞书记录ID',
  `style_no` VARCHAR(200) NOT NULL COMMENT '飞书款号/SPU',
  `shop_name` VARCHAR(200) DEFAULT '' COMMENT '店铺',
  `task_text` VARCHAR(500) DEFAULT '' COMMENT '飞书开款任务文本',
  `season_field` VARCHAR(100) DEFAULT '' COMMENT '飞书季节字段原始可读值',
  `product_line_field` VARCHAR(100) DEFAULT '' COMMENT '飞书品线字段，正式匹配优先使用',
  `product_line_from_task` VARCHAR(100) DEFAULT '' COMMENT '开款任务中解析出的品线，仅用于校验',
  `used_product_line` VARCHAR(100) DEFAULT '' COMMENT '最终使用的品线，当前规则为飞书品线字段优先',
  `year_group` VARCHAR(50) DEFAULT '' COMMENT '解析后的年份归类：历史/24/25/26/27等',
  `season` VARCHAR(50) DEFAULT '' COMMENT '解析后的季节：春夏/秋冬',
  `target_category_path` VARCHAR(800) DEFAULT '' COMMENT '目标领星分类路径',
  `target_category_id` BIGINT DEFAULT NULL COMMENT '匹配到的领星分类ID',
  `target_category_name` VARCHAR(200) DEFAULT '' COMMENT '匹配到的领星分类名称',
  `match_status` VARCHAR(50) NOT NULL DEFAULT 'pending' COMMENT 'matched/warning/invalid/not_found/duplicate',
  `match_message` VARCHAR(1000) DEFAULT '' COMMENT '匹配说明或风险提示',
  `style_no_count` INT NOT NULL DEFAULT 1 COMMENT '同一款号在本次飞书数据中的出现次数',
  `is_duplicate` TINYINT NOT NULL DEFAULT 0 COMMENT '同一款号是否重复：0否，1是',
  `raw_json` JSON NULL COMMENT '飞书原始记录',
  `synced_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '同步时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_record_id` (`record_id`),
  KEY `idx_style_no` (`style_no`),
  KEY `idx_target_category_id` (`target_category_id`),
  KEY `idx_target_category_path` (`target_category_path`(255)),
  KEY `idx_match_status` (`match_status`),
  KEY `idx_is_duplicate` (`is_duplicate`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='lx-product-m：飞书款号到领星分类匹配表';
